# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Bryan Absher
tagline:          'AAA Rockstar developer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://babsher.github.io
baseurl:          /

author:
  name:           'Bryan Absher'
  url:            https://twitter.com/AbsherBryan

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/babsher
